export const Images = {
  AppLogo: require("./Image/Group.png"),
  Profile: require("./Image/Profile.png"),
  MyEarning: require("./Image/MyEarnings.png"),
  MyCare: require("./Image/MyCarePortfolio.png"),
  Providers: require("./Image/Providers.png"),
  notification: require("./Image/notification.png"),
  searchnormal: require("./Image/searchnormal.png"),
  calendar: require("./Image/calendar.png"),
  Logout: require("./Image/Logout.png"),
  planbg: require("./Image/planbg.png"),
  VisaCard: require("./Image/VisaCard.png"),
  MembershipCard: require("./Image/MembershipCard.png"),
  PreventiveExams_Member: require("./Image/PreventiveExams_Member.png"),
  MyReimbursements_Member: require("./Image/MyReimbursements_Member.png"),
};
